#@follow_tag(registry-proxy.engineering.redhat.com/rh-osbs/openshift-golang-builder:v1.21)
FROM registry-proxy.engineering.redhat.com/rh-osbs/openshift-golang-builder:v1.21.9-202404231038.g1ac3e39.el8 AS builder

COPY $REMOTE_SOURCE $REMOTE_SOURCE_DIR

WORKDIR ${REMOTE_SOURCE_DIR}/app/

# Build
RUN CI_UPSTREAM_VERSION=$CI_CONTAINER_VERSION CI_COMMIT=$CI_UPSTREAM_COMMIT ./hack/build.sh

#@follow_tag(registry.redhat.io/ubi9/ubi:latest)
FROM registry.redhat.io/ubi9/ubi:9.4-947.1714667021

WORKDIR /
COPY --from=builder ${REMOTE_SOURCE_DIR}/app/bin/manager .
COPY --from=builder /$REMOTE_SOURCE_DIR/app/install/ /install/


ENTRYPOINT ["/manager"]

USER ${USER_UID}

LABEL com.redhat.component="self-node-remediation-operator-container" \
      name="red-hat-workload-availability/self-node-remediation" \
      version="${CI_CONTAINER_VERSION}" \
      release="${CI_CONTAINER_RELEASE}" \
      upstream-version="${CI_SELF_NODE_REMEDIATION_UPSTREAM_VERSION}" \
      upstream-vcs-ref="${CI_SELF_NODE_REMEDIATION_UPSTREAM_COMMIT}" \
      upstream-vcs-type="git" \
      description="OpenShift Self Node Remediation which is an OLM installable operator that install the Self Node Remediation agent" \
      summary="OpenShift Self Node Remediation" \
      io.openshift.tags="rhwa,snr,remediation" \
      io.k8s.display-name="OpenShift Self Node Remediation" \
      maintainer="Dragonfly Team <team-dragonfly@redhat.com>" 

