#@follow_tag(registry-proxy.engineering.redhat.com/rh-osbs/openshift-golang-builder:1.15)
FROM registry-proxy.engineering.redhat.com/rh-osbs/openshift-golang-builder:v1.15.14-202111041714.el7.git.897eb48 AS builder

COPY $REMOTE_SOURCE $REMOTE_SOURCE_DIR

WORKDIR ${REMOTE_SOURCE_DIR}/app/

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go

#@follow_tag(registry.redhat.io/ubi8/ubi:latest)
FROM registry.redhat.io/ubi8/ubi:8.6-754

COPY --from=builder /$REMOTE_SOURCE_DIR/app/manager /manager

ENTRYPOINT ["/manager"]

USER ${USER_UID}

LABEL com.redhat.component="poison-pill-container" \
      name="openshift4/poison-pill-rhel8" \
      version="${CI_CONTAINER_VERSION}" \
      upstream_commit="${CI_POISON_PILL_UPSTREAM_COMMIT}" \
      summary="OpenShift Poison Pill" \
      io.k8s.display-name="OpenShift Poison Pill" \
      maintainer="Dragonfly Team <kni-lifecycle-team@redhat.com>" \
      description="OpenShift Poison Pill"
