#@follow_tag(registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-must-gather:v4.10)
FROM registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-must-gather:v4.10.0-202205190747.p0.ge1c9bc4.assembly.stream

COPY $REMOTE_SOURCE $REMOTE_SOURCE_DIR

RUN mv /usr/bin/gather{,_original} && \
    cp $REMOTE_SOURCE_DIR/app/collection-scripts/* /usr/bin

ENTRYPOINT /usr/bin/gather

LABEL com.redhat.component="self-node-remediation-must-gather-container" \
      name="red-hat-workload-availability/self-node-remediation-must-gather-rhel8" \
      version="${CI_CONTAINER_VERSION}" \
      upstream_commit="${CI_MUST_GATHER_UPSTREAM_COMMIT}" \
      summary="Self Node Remediation Must Gather image" \
      io.openshift.expose-services="" \
      io.openshift.tags="rhwa,lifecycle,node,maintenance,logs" \
      io.k8s.display-name="Self Node Remediation Must Gather Imgae" \
      maintainer="Dragonfly Team <team-dragonfly@redhat.com>" \
      description="Self Node Remediation Must Gather is a tool that integrates which OCP must-gather utility to collect debug info related to Self Node Remediation"
