#!/bin/bash
#

# no need for that

#set -e
#set -x
#set -u
#set -o pipefail


#if [[ -z "${POISON_PILL_IMAGE_PULL_URL}" ]]; then
#    echo "POISON_PILL_IMAGE_PULL_URL env var not set"
#    exit 1
#fi

# we use = as delimiter since POISON_PILL_IMAGE_PULL_URL probably containes / which can interfere with a / delimiter
#sed -i "s=image: .*=image: ${POISON_PILL_IMAGE_PULL_URL}=" manifests/poison-pill-manager-config_v1_configmap.yaml
#sed -i "s=image: .*=image: ${POISON_PILL_IMAGE_PULL_URL}=" config/manager/controller_manager_config.yaml
