#@follow_tag(registry-proxy.engineering.redhat.com/rh-osbs/openshift-golang-builder:1.16)
FROM registry-proxy.engineering.redhat.com/rh-osbs/openshift-golang-builder:v1.16.12-202202120022.el7.g8382039 AS builder

COPY $REMOTE_SOURCE $REMOTE_SOURCE_DIR

WORKDIR ${REMOTE_SOURCE_DIR}/app/

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go

#@follow_tag(registry.redhat.io/ubi8/ubi:latest)
FROM registry.redhat.io/ubi8/ubi:8.6-754

COPY --from=builder /$REMOTE_SOURCE_DIR/app/manager /manager
COPY --from=builder /$REMOTE_SOURCE_DIR/app/install/ /install/


ENTRYPOINT ["/manager"]

USER ${USER_UID}

LABEL com.redhat.component="poison-pill-manager-operator-container" \
      name="openshift4/poison-pill-manager-rhel8-operator" \
      version="${CI_CONTAINER_VERSION}" \
      upstream_commit="${CI_POISON_PILL_UPSTREAM_COMMIT}" \
      summary="OpenShift Poison Pill Manager" \
      io.k8s.display-name="OpenShift Poison Pill Manager" \
      maintainer="Dragonfly Team <kni-lifecycle-team@redhat.com>" \
      description="OpenShift Poison Pill Manager which is an OLM installable operator that install the poison pill agent"

